#define INCLUDE_PATH "E:/workspace/myRenderer/source/generate1;E:/workspace/myRenderer/3rd/VulkanSDK/1.2.198.1/Include;E:/workspace/myRenderer/3rd/glfw/include;E:/workspace/myRenderer/3rd/stb/include;E:/workspace/myRenderer/3rd/glm-0.9.9.8;E:/workspace/myRenderer/3rd/shaderc/include;E:/workspace/myRenderer/3rd/rapidjson/include;E:/workspace/myRenderer/3rd/json/include;E:/workspace/myRenderer/3rd/msgpack/include;E:/workspace/myRenderer/3rd/LLVM/include;E:/workspace/myRenderer/3rd/mustache/include;E:/workspace/myRenderer/source"
#define PROJECT_PATH "E:/workspace/myRenderer"
#define SOURCE_PATH "E:/workspace/myRenderer/source"
#define SHADER_PATH "E:/workspace/myRenderer/shaders"
#define RESOURCE_PATH "E:/workspace/myRenderer/resource"
#define SHADER_FILE(T) "E:/workspace/myRenderer/shaders/"#T
#define RESOURCE_FILE(T) "E:/workspace/myRenderer/resource/"#T
#define CR_TEMPLATE_FILE(T) "E:/workspace/myRenderer/source/Tools/CppReflection/Private/Template/"#T
#define CR_GENERATE_PUBLIC_FILE(T) "E:/workspace/myRenderer/source/Generate/Public/"#T
#define CR_GENERATE_PRIVATE_FILE(T) "E:/workspace/myRenderer/source/Generate/Private/"#T
